version: '3'
services:
  elas:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.13.1
    container_name: elas
    environment:
#      - node.name=es01
#      - cluster.name=es-docker-cluster
      - discovery.type=single-node
#      - cluster.initial_master_nodes=es01,es02,es03
#      - bootstrap.memory_lock=true
#      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
#    volumes:
#      - data01:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
#    networks:
#      - elastic