version: "3"
services:
  mongoclient:
    image: mongoclient/mongoclient:2.2.0
    ports:
      - 3000:3000
    depends_on:
      - mongodb

  mongodb:
    image: mongo:4.4
    environment:
      MONGO_INITDB_DATABASE: pddb
#      MONGO_INITDB_ROOT_USERNAME: pond
#      MONGO_INITDB_ROOT_PASSWORD: 1234
    volumes:
      - "$PWD/data:/data/db"
    ports:
      - 28017:27017

  redis:
    image: "redis:alpine3.13"
    ports:
      - 6379:6379
    volumes:
      - "$PWD/redis:/redis/cache"