version: "3"
services:

#  app:
#    image: pd:1.4.1
#    depends_on:
#      - mongodb
#    environment:
#      MONGODB_URI: "mongodb://mongodb:27017"
#    ports:
#      - 8080:8080
#    networks:
#      - backend
#
#
#  mongoclient:
#    image: mongoclient/mongoclient:2.2.0
#    ports:
#      - 3000:3000
#    depends_on:
#      - mongodb

  mongodb:
    image: mongo:4.4
    environment:
      MONGO_INITDB_DATABASE: mongodb
    volumes:
      - "$PWD/data:/data/db"
    ports:
      - 27017:27017
    networks:
      - backend

  redis:
    image: "redis:alpine3.13"
    ports:
      - 6379:6379
    volumes:
      - "$PWD/redis:/redis/cache"

networks:
  backend: